Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Layout/Tab:
  EnforcedStyle: tab
AllCops:
  NewCops: enable
require: rubocop-rails
